services:
  postgres:
    container_name: ring-postgres
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    restart: "no"
    volumes:
      - "ring-postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  redis:
    container_name: ring-redis
    image: "redis:7-alpine"
    command: ["redis-server", "--port", "8287", "--requirepass", "redis"]
    ports:
      - "8287:8287"
    restart: "no"
    volumes:
      - "ring-redis-data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "8287", "-a", "redis", "ping"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  ring-postgres-data:
  ring-redis-data:
