services:
  postgres:
    container_name: postgres
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ring

  redis:
    container_name: redis
    image: "redis:7-alpine"
    command: ["redis-server", "--port", "8287", "--requirepass", "redis"]
    ports:
      - "8287:8287"
    restart: always
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "8287", "-a", "redis", "ping"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_HOST=redis
      - REDIS_PORT=8287
      - REDIS_DB=0

  ring:
    build:
      context: ../
    container_name: ring
    depends_on:
      - postgres
    env_file:
      - ../src/.env
      - ../src/.env.development.local
    image: "ghcr.io/wolfstar-project/ring:latest"
    ports:
      - "8282:8282"
      - "7282:7282"
    restart: always
    tty: true

volumes:
  postgres-data:
    external: true
